app = "ci-cd-java-lab" # à adapter avec le nom généré par Fly.io
primary_region = "cdg" # Paris, ou "ams" pour Amsterdam

[build]
  image = "desmonsf/ci-cd-java-lab" # sera utilisé plus tard si tu pushes une image

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

